name: mymast
services:
  mongodb:
    build:
      context: .
      dockerfile: ./Mongo.Dockerfile
      args:
          - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
          - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
          - MONGO_INITDB_ROOT_DATABASE=${MONGO_INITDB_ROOT_DATABASE}
          - MONGO_USER=${MONGO_USER}
          - MONGO_PASSWORD=${MONGO_PASSWORD}
    # env_file: "./mongo.env"
    environment:
      # to be configured within Coolify
      - SERVICE_FQDN_MONGODB
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_DATABASE=${MONGO_INITDB_ROOT_DATABASE}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
volumes:
  mongo_data: